name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23.1' ]
    name: Go ${{ matrix.go }} tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Install dependencies
      run: |
        go get -t -d -v ./...
        go install github.com/onsi/ginkgo/v2/ginkgo@latest
        go get -u golang.org/x/lint/golint
        go get -u github.com/modocache/gover
        go get -u github.com/mattn/goveralls
    - name: Setup Go path
      run: |
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    - name: Run tests
      run: |
        ginkgo -r -cover --randomize-all --randomize-suites --fail-on-pending --trace --show-node-events
        ginkgo -tags=gorillamux -r --randomize-suites --fail-on-pending --trace
        ginkgo -tags=gingonic -r --randomize-suites --fail-on-pending --trace
        ginkgo -tags=echo -r --randomize-suites --fail-on-pending --trace
        bash scripts/fmtpolice
        gover
        goveralls -coverprofile=gover.coverprofile -repotoken UWegKzoOH1o1QD9e5JKtvDt77JJc4lzVN
  
